services:
  - type: web
    name: crypto-news-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: "8922198966:AAGFf0zzu-uUYjdghOW5aWRfwK59wBKU4OY"
      - key: CHANNEL_ID
        value: "@cryptopahan1"